//! Fetches card data and art into a data directory.
//!
//! A Rust port of what was `tools/ingest/fetch_cards.py`. The Python version
//! was fine while this only ran from a checkout, but a shipped desktop binary
//! cannot require `python3` — it is absent by default on Windows, where the
//! name often resolves to a Store stub that opens the Store rather than running
//! anything.
//!
//! Source: <https://github.com/buhbbl/punk-records> — static versioned JSON
//! generated by vegapull from the official Bandai site. Card text and images
//! are Bandai's copyright; everything here writes to a user data directory and
//! nothing is vendored into the binary.
//!
//! One request per product: upstream publishes a per-pack aggregate carrying
//! the same fields as the individual card files, so fetching every set is 59
//! requests rather than ~2,700. The GitHub API is not used at all, so the
//! unauthenticated 60-per-hour limit never applies.

use std::collections::BTreeMap;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Mutex;
use std::time::Duration;

use serde::Deserialize;

/// The upstream revision this build fetches from.
///
/// Pinned to a commit, not a branch. A released binary that tracked `main`
/// would change behaviour whenever a third party edited their repository, and
/// break outright if it were renamed or restructured — with no recourse for
/// anyone who had already installed. Pinning trades automatic new sets for a
/// build that keeps working.
///
/// Bumping it is deliberate: pick a commit, update this, re-run the tests.
/// `OPSIM_SOURCE_REF` overrides it for trying a newer revision without a
/// rebuild.
pub const SOURCE_REF: &str = "2a48b092cf4c77acbe22367b8334bbc75102c702";

/// Environment variable that overrides [`SOURCE_REF`].
const SOURCE_REF_ENV: &str = "OPSIM_SOURCE_REF";

/// The revision an override selects, or the pin when there is none.
///
/// Kept separate from the environment so it can be exercised without writing a
/// process-global variable: two tests that disagree about what the variable
/// should say cannot both hold it at once, and the harness runs them on
/// parallel threads.
fn resolve_source_ref(override_ref: Option<&str>) -> &str {
    override_ref.unwrap_or(SOURCE_REF)
}

/// The revision actually in effect, [`SOURCE_REF`] unless overridden.
///
/// Worth recording alongside anything derived from card data: a session log
/// replayed against a different revision can diverge for reasons that are not
/// the engine's fault.
pub fn source_ref() -> String {
    resolve_source_ref(std::env::var(SOURCE_REF_ENV).ok().as_deref()).to_string()
}

/// Upstream root for a given revision.
pub fn source_root_for(git_ref: &str) -> String {
    format!("https://raw.githubusercontent.com/buhbbl/punk-records/{git_ref}/english")
}

/// Upstream root for the revision in effect.
pub fn source_root() -> String {
    source_root_for(&source_ref())
}

const RETRIES: u32 = 4;
const TIMEOUT: Duration = Duration::from_secs(30);

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("network error fetching {url}: {source}")]
    Http {
        url: String,
        #[source]
        source: Box<ureq::Error>,
    },
    #[error("io error at {path}: {source}")]
    Io {
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error("malformed json from {url}: {source}")]
    Json {
        url: String,
        #[source]
        source: serde_json::Error,
    },
    #[error("unknown pack name(s): {0}")]
    UnknownPacks(String),
}

/// Progress, for a caller driving a bar and a log.
pub enum Progress<'a> {
    /// Human-facing line.
    Message(String),
    /// Counter for a progress bar.
    Counter {
        phase: &'a str,
        current: u64,
        total: u64,
    },
}

/// What to fetch.
#[derive(Debug, Clone)]
pub struct Plan {
    /// Pack names, or empty for every pack.
    pub packs: Vec<String>,
    /// Also cache card art for the selected packs.
    pub images: bool,
    /// Re-download packs already on disk.
    pub refresh: bool,
    /// Parallel downloads. Kept low deliberately: an earlier version fetched
    /// one file per *card* across 8 workers and GitHub responded by stalling
    /// the TLS handshake until the run died.
    pub jobs: usize,
}

impl Default for Plan {
    fn default() -> Plan {
        Plan {
            packs: vec!["ST-01".into(), "ST-02".into()],
            images: false,
            refresh: false,
            jobs: 4,
        }
    }
}

#[derive(Debug, Default)]
pub struct Summary {
    pub cards: usize,
    pub products: usize,
    pub images_fetched: usize,
    pub failed: Vec<String>,
}

#[derive(Debug, Deserialize)]
struct PackMeta {
    raw_title: Option<String>,
    title_parts: Option<TitleParts>,
}

#[derive(Debug, Deserialize)]
struct TitleParts {
    label: Option<String>,
}

#[derive(Debug, Deserialize, serde::Serialize)]
struct RawCard {
    id: String,
    #[serde(default)]
    img_full_url: Option<String>,
    #[serde(flatten)]
    rest: serde_json::Map<String, serde_json::Value>,
}

/// `"ST-01"`, `"st01"` and `"ST 01"` all key the same pack.
pub fn normalize(name: &str) -> String {
    name.chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .map(|c| c.to_ascii_uppercase())
        .collect()
}

/// Alternate printings — `OP01-016_p1`, `EB01-006_r1`.
///
/// The same card as their base, including for the four-copy deck limit
/// (5-1-2-3), so registering them separately would let a deck field eight.
pub fn is_art_variant(card_id: &str) -> bool {
    card_id.contains('_')
}

/// Packs upstream leaves unlabelled. Promos are tournament-legal, so they need
/// to be reachable by name.
fn unlabelled_aliases(raw_title: &str) -> &'static [&'static str] {
    match raw_title {
        "Promotion card" => &["PROMO", "P"],
        "Other Product Card" => &["OTHER"],
        _ => &[],
    }
}

/// Every name a pack answers to.
///
/// Upstream labels are not always one product code: OP-14 and OP-15 ship as
/// combined products labelled `OP14-EB04` and `OP15-EB04`, so each component is
/// registered separately and a shared component resolves to both.
fn pack_aliases(meta: &PackMeta) -> Vec<String> {
    let label = meta.title_parts.as_ref().and_then(|t| t.label.as_deref());
    let Some(label) = label else {
        return meta
            .raw_title
            .as_deref()
            .map(unlabelled_aliases)
            .unwrap_or(&[])
            .iter()
            .map(|a| normalize(a))
            .collect();
    };

    let mut names = vec![normalize(label)];
    for part in label.split('-') {
        // A product code is letters then digits: "OP14", "EB04". This skips the
        // bare "ST"/"01" halves of an ordinary label, already covered above.
        let is_code = !part.is_empty()
            && part.chars().take_while(|c| c.is_ascii_alphabetic()).count() > 0
            && part
                .chars()
                .skip_while(|c| c.is_ascii_alphabetic())
                .all(|c| c.is_ascii_digit())
            && part.chars().any(|c| c.is_ascii_digit());
        if is_code {
            let n = normalize(part);
            if !names.contains(&n) {
                names.push(n);
            }
        }
    }
    names
}

struct Client {
    agent: ureq::Agent,
}

impl Client {
    fn new() -> Client {
        Client {
            agent: ureq::AgentBuilder::new()
                .timeout(TIMEOUT)
                .user_agent("OnePieceSim-ingest")
                .build(),
        }
    }

    /// Fetches a URL, retrying transient failures with exponential backoff.
    ///
    /// Connection timeouts are the common failure when pulling many files —
    /// GitHub stalls the handshake rather than refusing it — so transport
    /// errors are retried, not just bad statuses. A 404 is a real answer and is
    /// returned immediately.
    fn get(&self, url: &str) -> Result<Vec<u8>, Error> {
        let mut last: Option<ureq::Error> = None;
        for attempt in 0..RETRIES {
            match self.agent.get(url).call() {
                Ok(response) => {
                    let mut buf = Vec::new();
                    if let Err(source) = response.into_reader().read_to_end(&mut buf) {
                        last = Some(ureq::Error::from(source));
                        continue;
                    }
                    return Ok(buf);
                }
                Err(ureq::Error::Status(404, r)) => {
                    return Err(Error::Http {
                        url: url.into(),
                        source: Box::new(ureq::Error::Status(404, r)),
                    })
                }
                Err(err) => last = Some(err),
            }
            if attempt + 1 < RETRIES {
                std::thread::sleep(Duration::from_secs(1 << attempt));
            }
        }
        Err(Error::Http {
            url: url.into(),
            source: Box::new(last.expect("a failed attempt records an error")),
        })
    }
}

fn write(path: &Path, bytes: &[u8]) -> Result<(), Error> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|source| Error::Io {
            path: parent.display().to_string(),
            source,
        })?;
    }
    std::fs::write(path, bytes).map_err(|source| Error::Io {
        path: path.display().to_string(),
        source,
    })
}

/// Runs the ingest, reporting progress as it goes.
///
/// Blocking — call it on a worker thread.
pub fn run(
    data_dir: &Path,
    plan: &Plan,
    progress: &(dyn Fn(Progress) + Sync),
) -> Result<Summary, Error> {
    let client = Client::new();
    let cards_dir = data_dir.join("cards");

    progress(Progress::Message("Fetching pack index…".into()));
    let root = source_root();
    let index_url = format!("{root}/packs.json");
    let raw = client.get(&index_url)?;
    write(&data_dir.join("packs.json"), &raw)?;
    let packs: BTreeMap<String, PackMeta> =
        serde_json::from_slice(&raw).map_err(|source| Error::Json {
            url: index_url,
            source,
        })?;

    // alias -> pack ids. A name may resolve to several products: EB-04 shipped
    // inside both the OP-14 and OP-15 boosters.
    let mut by_alias: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for (pack_id, meta) in &packs {
        for alias in pack_aliases(meta) {
            by_alias.entry(alias).or_default().push(pack_id.clone());
        }
    }

    // Selection, deduplicated by product so two names for one pack fetch once.
    let mut selected: Vec<String> = Vec::new();
    if plan.packs.is_empty() {
        selected.extend(packs.keys().cloned());
    } else {
        let unknown: Vec<&str> = plan
            .packs
            .iter()
            .filter(|p| !by_alias.contains_key(&normalize(p)))
            .map(|p| p.as_str())
            .collect();
        if !unknown.is_empty() {
            return Err(Error::UnknownPacks(unknown.join(", ")));
        }
        for name in &plan.packs {
            for pack_id in &by_alias[&normalize(name)] {
                if !selected.contains(pack_id) {
                    selected.push(pack_id.clone());
                }
            }
        }
    }

    progress(Progress::Message(format!(
        "Fetching {} product(s)…",
        selected.len()
    )));

    let mut summary = Summary {
        products: selected.len(),
        ..Summary::default()
    };
    progress(Progress::Counter {
        phase: "packs",
        current: 0,
        total: selected.len() as u64,
    });

    for (done, pack_id) in selected.iter().enumerate() {
        let dest = cards_dir.join(format!("{pack_id}.json"));
        let cards = if dest.exists() && !plan.refresh {
            read_pack(&dest).unwrap_or_default()
        } else {
            let url = format!("{root}/data/{pack_id}.json");
            match client.get(&url) {
                Ok(bytes) => {
                    let all: Vec<RawCard> =
                        serde_json::from_slice(&bytes).map_err(|source| Error::Json {
                            url: url.clone(),
                            source,
                        })?;
                    let kept: Vec<RawCard> =
                        all.into_iter().filter(|c| !is_art_variant(&c.id)).collect();
                    let json = serde_json::to_vec_pretty(&kept)
                        .map_err(|source| Error::Json { url, source })?;
                    write(&dest, &json)?;
                    kept
                }
                Err(err) => {
                    // One unreachable product must not discard the rest of the
                    // run; re-running picks up only what is missing.
                    progress(Progress::Message(format!("  {pack_id} failed: {err}")));
                    summary.failed.push(pack_id.clone());
                    Vec::new()
                }
            }
        };
        summary.cards += cards.len();
        progress(Progress::Counter {
            phase: "packs",
            current: done as u64 + 1,
            total: selected.len() as u64,
        });
    }

    if plan.images {
        summary.images_fetched = fetch_images(&client, data_dir, &selected, plan, progress)?;
    }

    Ok(summary)
}

fn read_pack(path: &Path) -> Option<Vec<RawCard>> {
    serde_json::from_slice(&std::fs::read(path).ok()?).ok()
}

/// Caches card art for the given products, skipping what is already on disk.
fn fetch_images(
    client: &Client,
    data_dir: &Path,
    pack_ids: &[String],
    plan: &Plan,
    progress: &(dyn Fn(Progress) + Sync),
) -> Result<usize, Error> {
    let images_dir = data_dir.join("images");
    std::fs::create_dir_all(&images_dir).map_err(|source| Error::Io {
        path: images_dir.display().to_string(),
        source,
    })?;

    let mut wanted: Vec<(String, String)> = Vec::new();
    for pack_id in pack_ids {
        let Some(cards) = read_pack(&data_dir.join("cards").join(format!("{pack_id}.json"))) else {
            continue;
        };
        for card in cards {
            if let Some(url) = card.img_full_url {
                if !images_dir.join(format!("{}.png", card.id)).exists() {
                    wanted.push((card.id, url));
                }
            }
        }
    }

    if wanted.is_empty() {
        progress(Progress::Message("Card art already cached".into()));
        return Ok(0);
    }
    progress(Progress::Message(format!(
        "Caching {} card image(s)…",
        wanted.len()
    )));

    let total = wanted.len() as u64;
    let done = AtomicU64::new(0);
    let fetched = AtomicU64::new(0);
    let queue = Mutex::new(wanted.into_iter());
    progress(Progress::Counter {
        phase: "images",
        current: 0,
        total,
    });

    std::thread::scope(|scope| {
        for _ in 0..plan.jobs.max(1) {
            scope.spawn(|| loop {
                let Some((id, url)) = queue.lock().expect("queue lock").next() else {
                    return;
                };
                if let Ok(bytes) = client.get(&url) {
                    if write(&images_dir.join(format!("{id}.png")), &bytes).is_ok() {
                        fetched.fetch_add(1, Ordering::Relaxed);
                    }
                }
                let n = done.fetch_add(1, Ordering::Relaxed) + 1;
                // Throttled: smooth enough for a bar without thousands of
                // updates.
                if n.is_multiple_of(10) || n == total {
                    progress(Progress::Counter {
                        phase: "images",
                        current: n,
                        total,
                    });
                }
            });
        }
    });

    Ok(fetched.load(Ordering::Relaxed) as usize)
}

/// Whether `cards_dir` holds anything loadable.
pub fn is_populated(cards_dir: &Path) -> bool {
    std::fs::read_dir(cards_dir)
        .map(|mut entries| {
            entries.any(|e| {
                e.map(|e| e.path().extension().is_some_and(|x| x == "json"))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

/// Default data directory: the platform's per-user application data location.
///
/// Never the install directory — it is not user-writable on Windows or macOS,
/// and a shipped binary has no repository to write into.
pub fn default_data_dir(app_id: &str) -> PathBuf {
    #[cfg(target_os = "macos")]
    let base =
        std::env::var_os("HOME").map(|h| PathBuf::from(h).join("Library/Application Support"));
    #[cfg(target_os = "windows")]
    let base = std::env::var_os("APPDATA").map(PathBuf::from);
    #[cfg(all(unix, not(target_os = "macos")))]
    let base = std::env::var_os("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/share")));

    base.unwrap_or_else(std::env::temp_dir).join(app_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meta(label: Option<&str>, raw: &str) -> PackMeta {
        PackMeta {
            raw_title: Some(raw.into()),
            title_parts: Some(TitleParts {
                label: label.map(|l| l.into()),
            }),
        }
    }

    #[test]
    fn names_ignore_case_and_punctuation() {
        for name in ["ST-01", "st01", "ST 01", "st-01"] {
            assert_eq!(normalize(name), "ST01");
        }
    }

    #[test]
    fn compound_labels_register_each_product_code() {
        // OP-14 ships as a combined product; both halves must resolve.
        let aliases = pack_aliases(&meta(Some("OP14-EB04"), "BOOSTER PACK"));
        assert!(aliases.contains(&"OP14EB04".to_string()));
        assert!(aliases.contains(&"OP14".to_string()));
        assert!(aliases.contains(&"EB04".to_string()));
    }

    #[test]
    fn an_ordinary_label_does_not_split_into_halves() {
        // "ST-01" must not register a bare "ST" or "01".
        let aliases = pack_aliases(&meta(Some("ST-01"), "STARTER DECK"));
        assert_eq!(aliases, vec!["ST01".to_string()]);
    }

    #[test]
    fn unlabelled_packs_are_reachable_by_name() {
        assert_eq!(
            pack_aliases(&meta(None, "Promotion card")),
            vec!["PROMO".to_string(), "P".to_string()]
        );
        assert_eq!(
            pack_aliases(&meta(None, "Other Product Card")),
            vec!["OTHER".to_string()]
        );
    }

    #[test]
    fn alternate_printings_are_recognised() {
        assert!(is_art_variant("OP01-016_p1"));
        assert!(is_art_variant("EB01-006_r1"));
        assert!(!is_art_variant("OP01-016"));
        assert!(!is_art_variant("P-001"));
    }

    /// A pinned ref is only useful if it is a commit. A branch name here would
    /// silently reintroduce the drift the pin exists to prevent.
    #[test]
    fn the_source_is_pinned_to_a_commit_not_a_branch() {
        assert_eq!(SOURCE_REF.len(), 40, "expected a full commit sha");
        assert!(
            SOURCE_REF.chars().all(|c| c.is_ascii_hexdigit()),
            "expected hex, got {SOURCE_REF}"
        );
        assert!(source_root_for(SOURCE_REF).contains(SOURCE_REF));
    }

    /// Absent an override, the pin is what everything downstream fetches from.
    #[test]
    fn the_pin_is_what_applies_when_nothing_overrides_it() {
        assert_eq!(resolve_source_ref(None), SOURCE_REF);
    }

    #[test]
    fn the_source_ref_can_be_overridden_without_a_rebuild() {
        let overridden = source_root_for(resolve_source_ref(Some("main")));
        assert!(overridden.ends_with("/main/english"));
        assert!(!overridden.contains(SOURCE_REF));
    }

    #[test]
    fn the_data_directory_is_never_the_install_directory() {
        let dir = default_data_dir("dev.example.app");
        assert!(dir.ends_with("dev.example.app"));
        assert!(dir.is_absolute());
    }
}
