[package]
name = "op-cards"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
op-core = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[[bin]]
name = "coverage"
path = "src/bin/coverage.rs"

[[bin]]
name = "dump-scripts"
path = "src/bin/dump_scripts.rs"
